// src/app/core/components/left-nav/left-nav.component.ts
import { Component } from '@angular/core';
import { MenuItem } from '../../models/MenuItem';


@Component({
  selector: 'left-nav',
  templateUrl: './left-nav.component.html',
  styleUrls: ['./left-nav.component.scss']
})

export class LeftNavComponent {
  menuItems: MenuItem[];
  constructor() {
    this.menuItems = [
      new MenuItem('Dashboard', "https://picsum.photos/200?random=" + Math.floor(Math.random() * 9999), '/dashboard', []),
      new MenuItem('Workflows', "https://picsum.photos/200?random=" + Math.floor(Math.random() * 9999), '/workflows', []),
      new MenuItem('Chat', "https://picsum.photos/200?random=" + Math.floor(Math.random() * 9999), '/chat', [])
    ];
  }
}

<ul class="left-nav">
    <li  *ngFor="let menuItem of menuItems">
        <a [routerLink]="menuItem.route" routerLinkActive="active">
            <img [src]="menuItem.iconUrl" alt="icon" />
            {{menuItem.title}}
        </a>
    </li>
</ul>

// src/components/left-nav/LeftNav.tsx
import React from 'react';
import './LeftNav.scss';
import Avatar from '@mui/material/Avatar';
import Stack from '@mui/material/Stack';
import { CardHeader } from '@mui/material';

class LeftNav extends React.Component {
    seed: number;
    constructor(props: any) {
        super(props);
        this.seed = Math.floor(Math.random() * 9999);
    }
    override render() {
        return (
            <div className="left-nav bg-lush">
                <Stack className="user-stack" direction="row" spacing={1}>
                    <CardHeader className="user-card"
                        avatar={
                            <Avatar
                                alt="Hazel"
                                src={`https://picsum.photos/200?random=${this.seed}`}
                            />
                        }
                        title="Hazel"
                    />
                </Stack>
            </div>
        );
    }
}

export default LeftNav;
